//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ntobjx.rc
//
#define IDR_MAINFRAME                   1
#define IDS_PROGRAM_DESCRIPTION         2
#define IDS_ABOUT_MENUITEM              3
#define IDS_STATUSBAR_ADMIN             4
#define IDS_STATUSBAR_NOTADMIN          5
#define IDS_STATUSBAR_ELEVATED          6
#define IDS_OBJSPEC_NAME1_EVENT         7
#define IDS_OBJSPEC_NAME2_EVENT         8
#define IDS_OBJSPEC_ATTR2_EVENT_SYNC    9
#define IDS_OBJSPEC_ATTR2_EVENT_NOTIFY  10
#define IDS_OBJSPEC_ERROR               11
#define IDS_OBJSPEC_INFO                12
#define IDS_OBJSPEC_NAME1_SYMLINK       13
#define IDS_STATUSBAR_NOTELEVATED       14
#define IDS_STATUSBAR_DIR_DETAILS       15
#define IDS_TITLEBAR_FMTSTR             16
#define IDS_FEATURE_UNAVAILABLE         17
#define IDS_NOT_AVAILABLE_SHORT         18
#define IDS_ABOUT                       19
#define IDS_OBJ_OPEN_STATUS             20
#define IDS_OBJ_QUERY_STATUS            21
#define IDS_UNKNOWN_FMTSTR              22
#define IDS_STATUS_DESCRIPTION          23
#define IDS_OBJSPEC_NAME1_WINSTA        24
#define IDS_OBJSPEC_NAME2_WINSTA        25
#define IDS_OBJSPEC_NAME3_WINSTA        26
#define IDS_URL_ONLINEHELP              27
#define IDD_PROPERTIES                  107
#define IDR_POPUP_MENU1                 202
#define IDD_ABOUT                       205
#define IDR_POPUP_HYPERLINK1            207
#define IDD_FIND_OBJECT                 209
#define IDD_SECURITY_NOT_AVAILABLE      210
#define IDS_OBJSPEC_NAME1_IOCOMPLETION  213
#define IDS_OBJSPEC_NAME1_KEY           214
#define IDS_OBJSPEC_NAME2_KEY           215
#define IDS_OBJSPEC_NAME1_MUTANT        216
#define IDS_OBJSPEC_NAME2_MUTANT        217
#define IDS_OBJSPEC_NAME3_MUTANT        218
#define IDS_OBJSPEC_NAME1_SECTION       219
#define IDS_OBJSPEC_NAME2_SECTION       220
#define IDS_OBJSPEC_NAME3_SECTION       221
#define IDS_OBJSPEC_NAME1_SEMAPHORE     222
#define IDS_OBJSPEC_NAME2_SEMAPHORE     223
#define IDS_OBJSPEC_NAME1_TIMER         224
#define IDS_OBJSPEC_NAME2_TIMER         225
#define IDS_OBJTT_ARCNAME               226
#define IDS_OBJTT_BASENAMEDOBJECTS      227
#define IDS_OBJTT_CALLBACK              228
#define IDS_OBJTT_DEVICE                229
#define IDS_OBJTT_DOSDEVICES            230
#define IDS_OBJTT_DRIVER                231
#define IDS_OBJTT_FILESYSTEM            232
#define IDS_OBJTT_GLOBALDOSDEV          233
#define IDS_OBJTT_KERNELOBJECTS         234
#define IDS_OBJTT_KNOWNDLLS             235
#define IDS_OBJTT_KNOWNDLLS32           236
#define IDS_OBJTT_NLS                   237
#define IDS_OBJTT_OBJECTTYPES           238
#define IDS_OBJTT_PSXSS                 239
#define IDS_OBJTT_RPCCTL                240
#define IDS_OBJTT_SECURITY              241
#define IDS_OBJTT_SESSIONS              242
#define IDS_OBJTT_UDFCOMMPORTS          243
#define IDS_OBJTT_WINDOWS               244
#define IDS_OBJTT_WINDOWSTATIONS        245
#define IDS_OBJTT_DOSDEV                246
#define IDS_OBJTT_SYSTEMROOT            247
#define IDS_OBJTT_MAILSLOT              248
#define IDS_OBJTT_NAMEDPIPE             249
#define IDS_OBJTT_PHYSMEM               250
#define IDS_OBJTT_REGISTRY              251
#define IDC_STATIC_PROGNAME             1000
#define IDC_STATIC_COPYRIGHT            1001
#define IDC_STATIC_DESCRIPTION          1002
#define IDC_STATIC_WEBSITE              1003
#define IDC_STATIC_PROJECT_WEBSITE      1004
#define IDC_STATIC_REVISION             1005
#define IDC_STATIC_PORTIONSCOPYRIGHT    1006
#define IDC_EDIT_NAME                   1010
#define IDC_EDIT_FULLNAME               1011
#define IDC_EDIT_TYPE                   1012
#define IDC_EXPLANATION_WHY             1015
#define IDC_NO_SECURITY_CAPTION         1016
#define IDC_REF_BYPTR                   1018
#define IDC_REF_BYHDL                   1019
#define IDC_QUOTA_PAGED                 1020
#define IDC_QUOTA_NONPAGED              1021
#define IDC_OBJ_CREATION_TIME           1022
#define IDC_GROUP_OBJSPECIFIC           1023
#define IDC_STATIC_OBJSPEC_NAME1        1024
#define IDS_ABOUT_DESCRIPTION           1025
#define IDC_STATIC_OBJSPEC_NAME2        1025
#define IDC_STATIC_OBJSPEC_NAME3        1026
#define IDC_STATIC_OBJSPEC_ATTR1        1027
#define IDC_STATIC_OBJSPEC_ATTR2        1028
#define IDC_STATIC_OBJSPEC_ATTR3        1029
#define ID_SWITCHLANGUAGE_GERMAN        1031
#define ID_SWITCHLANGUAGE_ENGLISH       1033
#define ID_VIEW_PROPERTIES              32774
#define ID_POPUPMENU_COPYNAME           32775
#define ID_POPUPMENU_COPYFULLPATH       32776
#define ID_POPUPMENU_COPYSYMLINKTARGET  32777
#define ID_POPUPMENU_COPYASCSTRING      32778
#define ID_POPUPMENU_PROPERTIES         32779
#define ID_COLNAME_OBJNAME              32780
#define ID_COLNAME_OBJTYPE              32781
#define ID_COLNAME_OBJLNKTGT            32782
#define ID_SHOW_ABOUT                   32783
#define IDS_PROPERTIES                  32784
#define ID_POPUPMENU_OPENDIRECTORY      32785
#define ID_POPUPMENU_COPYURL            32786
#define ID_VIEW_FIND                    32787
#define ID_SWITCHLANGUAGE_POPUP         32790
#define ID_SHOW_ONLINEHELP              32791

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        252
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1028
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
